
name: SAST Scan

on:
  push:
    branches: [master]

jobs:
  sast:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
    
      - name: Install dependencies
        run: |
          sudo apt update
          sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt install -y unzip nodejs
    
      - name: Install OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
          unzip dependency-check-6.0.2-release.zip
        
      - name: Run Dependency-Check Scan
        run: |
          dependency-check/bin/dependency-check.sh --scan . --out ./sast-report --format JSON --prettyPrint || true
        
      - name: Store scan reports (Archive production artifacts)
        uses: actions/upload-artifact@v2
        with:
          name: SAST Report
          path: |
            ./sast-report
