
name: SAST Scan

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: install dependencies
      run: | 
       sudo apt update
       sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
       sudo apt install -y nodejs

    - name: OWASP Dependency Check
      run: |
       wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
       unzip dependency-check-6.0.2-release.zip

    - name: Run scan with ODC
      run: |
        dependency-check/bin/dependency-check.sh --project "angular-realworld-example-app" --scan . > ODC-report || true

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sast report
        path: |
          ./ODC-report
