
name: SAST Scan

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: | 
       sudo apt update

    - name: Install OWASP Dependency-Check
      run: |
       wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.0.2/dependency-check-6.0.2-release.zip
       unzip dependency-check-6.0.2-release.zip

    - name: Run Dependency-Check scan
      run: |
        ls
        pwd
        ls ..
